// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0BCnbbd9fNJIO_AyTpxrtSUtKk1r61qE',
    appId: '1:311846400263:web:21181242c2f97f4c38d5a2',
    messagingSenderId: '311846400263',
    projectId: 'ritian',
    authDomain: 'ritian.firebaseapp.com',
    storageBucket: 'ritian.firebasestorage.app',
    measurementId: 'G-KBG48E47CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgsk67-LTMmluSNjZjzvq2Paw9qCLaV5w',
    appId: '1:311846400263:android:fb6385e44c1edc4338d5a2',
    messagingSenderId: '311846400263',
    projectId: 'ritian',
    storageBucket: 'ritian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0IFy3fIONivm7iBac7AOUD46zlmAlvc',
    appId: '1:311846400263:ios:1d7e172b3ce6bf5938d5a2',
    messagingSenderId: '311846400263',
    projectId: 'ritian',
    storageBucket: 'ritian.firebasestorage.app',
    iosBundleId: 'com.example.ritianCanteenV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS0IFy3fIONivm7iBac7AOUD46zlmAlvc',
    appId: '1:311846400263:ios:1d7e172b3ce6bf5938d5a2',
    messagingSenderId: '311846400263',
    projectId: 'ritian',
    storageBucket: 'ritian.firebasestorage.app',
    iosBundleId: 'com.example.ritianCanteenV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0BCnbbd9fNJIO_AyTpxrtSUtKk1r61qE',
    appId: '1:311846400263:web:ce098fc66ede21ed38d5a2',
    messagingSenderId: '311846400263',
    projectId: 'ritian',
    authDomain: 'ritian.firebaseapp.com',
    storageBucket: 'ritian.firebasestorage.app',
    measurementId: 'G-B494L4Q30D',
  );
}
